version: "3"
services:
  todo-app:
    image: "${IMAGE}"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: "27017"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
